#!/bin/bash

echo " *** startvnc script"
set -e

exec tigervncserver -localhost no -geometry 1024x768 :1


# Not using the below for now:

if [ ! -f ~/.vnc/passwd ]; then
  if [ -z "$VNCPASSWORD" ]; then
    VNCPASSWORD=`pwgen 8`
    echo " *** VNC password for this session: $VNCPASSWORD"
  fi

  export USER="`whoami`"
  mkdir -p ~/.vnc

  echo "$VNCPASSWORD" | tightvncpasswd -f > ~/.vnc/passwd
  chmod 0600 ~/.vnc/passwd
fi


