docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - umask 0022
    - apk add git
    - apk add curl
    - apk add bash
    - git submodule init
    - git submodule update
    - chmod -R og-w .
    - ./buildall
    - cd proxied-app-apache && docker build -t jgoerzen/proxied-app-apache .
    - cd ../reverse-proxy-apache && docker build -t jgoerzen/reverse-proxy-apache .
    - docker tag jgoerzen/mythtv-backend jgoerzen/mythtv-backend:33.1
    - docker tag jgoerzen/mythtv-backend-mysql jgoerzen/mythtv-backend-mysql:33.1
    - docker push jgoerzen/mythtv-backend
    - docker push jgoerzen/mythtv-backend:33.1
    - docker push jgoerzen/mythtv-backend-mysql
    - docker push jgoerzen/mythtv-backend-mysql:33.1
  only:
    - master
